### ISSUE TITLE
Port to fish shell?

### ISSUE THREAD

**Issue by DarremMolko** [tom-doerr/zsh_codex#10]
Hi. This looks like a fantastic idea and I'd like to try it out but I'm currently using fish. Would it be possible to port this as a plugin for Fisher or OMF?

**Comment by tom-doerr** [comment]
Might port it if I get to it. :)

**Comment by tom-doerr** [comment]
Here you go: https://github.com/tom-doerr/codex.fish
Please let me know if you experience issues.
