### ISSUE TITLE
Invalid Request error - Engine not found

### ISSUE THREAD

**Issue by stonelazy** [tom-doerr/zsh_codex#13]
Steps done to install zsh_codex  
1.) Installed openai using `pip install openai`
2.) Clone the repo with the given link, in my custom dir.  
3.) Added `source "$ZSH_CUSTOM/plugins/zsh_codex/zsh_codex.plugin.zsh"` to my .zshrc  
4.) Created openaipirc with the secrets generated from https://beta.openai.com/account/api-keys  

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/11377834/161468404-eb46fd90-7c75-4656-a110-eeae53695f83.png">

**Comment by tom-doerr** [comment]
Do you have access to Codex? Having access to the API is not sufficient,  see https://github.com/tom-doerr/vim_codex/issues/12

**Comment by stonelazy** [comment]
Oh ! I didn't know i need to have sufficient access for this. Thanks for the quick reply.
