### ISSUE TITLE
Fix engine name

### ISSUE THREAD

**Issue by thebenlamm** [tom-doerr/zsh_codex#15]
The engine name [here](https://github.com/tom-doerr/zsh_codex/blob/main/create_completion.py#L64) should be `text-davinci-002`

Love what you've done here. Good job!

**Comment by tom-doerr** [comment]
It works with `text-davinci-002`, but `code-davinci-002` works better. It probably doesn't work for you because you are not accepted for Codex, see: https://github.com/tom-doerr/zsh_codex/issues/13 .
