### ISSUE TITLE
Make it possible to use in mulitiple python environment 

### ISSUE THREAD

**Issue by Czaki** [tom-doerr/zsh_codex#17]
Hi, 
I'm a python developer who work with multiple python environments (at least one per project). I did not want to install openai in each environment. 

Maybe you could create python package in place of [`create_completion.py`](https://github.com/tom-doerr/zsh_codex/blob/main/create_completion.py) that could be installed with `pipx`?

**Comment by tom-doerr** [comment]
That's a really good idea

**Comment by tom-doerr** [comment]
However you would still need to install the shell files, so installation wouldn't be easier. How about I check if there is a python bin linked in `/usr/bin/python` and use that if it's available? That should solve your issue.

**Comment by Rizhiy** [comment]
A better approach is to allow user to set python executable)
