### ISSUE TITLE
[FR] Support for Additional Backends Compatible with OpenAI Protocol

### ISSUE THREAD

**Issue by wyg1997** [tom-doerr/zsh_codex#50]
It would be beneficial to add support for additional backends compatible with the OpenAI protocol, with the option to specify URLs through environment variables or a configuration file.

**Comment by tom-doerr** [comment]
Support for arbitrary OpenAI API compatible backends just got added: https://github.com/tom-doerr/zsh_codex/pull/49
Is this what you are looking for?

**Comment by wyg1997** [comment]
Thanks for your response and hard work! I'm glad to see that #49 addresses my issue perfectly. This is precisely what I needed. Thank you again, and I'm excited to see how the project evolves in the future!
