### ISSUE TITLE
gemini support

### ISSUE THREAD

**Issue by gustavodscruz** [tom-doerr/zsh_codex#59]
![image](https://github.com/user-attachments/assets/93ffa30f-31d1-4a12-baa6-1728a5e87148)
always than I trying to get auto-completion, throw this error to me, am I doing something wrong?

![image](https://github.com/user-attachments/assets/57d48dc5-2c32-4606-a714-68d3b33cede0)

**Comment by tom-doerr** [comment]
Your `api_type` is set to `gemeni` instead of `gemini`. This might cause the service to not be processed correctly. 
Please let me know if this doesn't fix the issue.

**Comment by gustavodscruz** [comment]
> Your `api_type` is set to `gemeni` instead of `gemini`. This might cause the service to not be processed correctly. Please let me know if this doesn't fix the issue.

yess, but also i made another thing wrong too loll, I wasn't made the file in the .config

but thanks so much for the response! I modified the .ini file to groq service too

congrats for the awesome plugin, it's excellent!
