### ISSUE TITLE
Execute generated command

### ISSUE THREAD

**Issue by fischer-felix** [tom-doerr/zsh_codex#7]
Maybe I'm just missing something here, but I can't seem to figure out how to acutally have zsh execute whatever codex comes up with, upon pressing enter, it complains about the # and if I press Ctrl+x again, it just generates more commands.
https://user-images.githubusercontent.com/65448408/139941453-7a4974c5-028c-4cfb-b9f6-4c59be16f42d.mp4

**Comment by tom-doerr** [comment]
Fancy desktop environment you got there. 

`set -k` should do the trick (https://unix.stackexchange.com/questions/33994/zsh-interpret-ignore-commands-beginning-with-as-comments).
Why is the auto completion shown for you before you hit Ctrl+X? Do you have Github Copilot in the command line?

**Comment by fischer-felix** [comment]
If You mean the grey-ish text, that is just dumb commands from my history. 
It does seem to be working with set -k as an option now though, thanks for the quick reply.
